export const HORIZONTAL_FOV = 90;   // Campo visual amplio para ver más rocas
export const VERTICAL_FOV   = 60;   // Campo vertical amplio
export const FOV_MARGIN     = 3;    // marge anti-bord pour éviter le clignotement
export const HEADING_OFFSET = 0;    // ajuste à +/– quelques degrés si besoin
export const MAX_DEPTH_METERS = 3000; // distance à partir de laquelle on considère "fond"
export const HYSTERESIS_DEG = 3;   // marge de grâce quand on sort à peine du cône 
export const VIS_STICK_MS = 600; //on conserve l'étiquette environ 0,8s après sortie du cône 
export const SMOOTHING_ALPHA_HEADING = .12;  // Lissage azimut (más estable)
export const SMOOTHING_ALPHA_PITCH = .15;    // Lissage pitch (más estable)
export const HEADING_DEADZONE = 2;         // Ignora cambios menores de 1.5°
export const PITCH_DEADZONE = 1.0;           // Ignora cambios menores de 1.0°
export const MIN_DISTANCE = 50;              // Distance minimale en mètres
export const MAX_DISTANCE = 5000;            // Distance maximale en mètres