export const HORIZONTAL_FOV = 90;   // Champ visuel large pour voir plus de rochers
export const VERTICAL_FOV   = 60;   // Champ vertical large
export const FOV_MARGIN     = 3;    // Marge anti-bord pour éviter le clignotement
export const HEADING_OFFSET = 0;    // Ajustement à +/- quelques degrés si nécessaire
export const MAX_DEPTH_METERS = 3000; // Distance à partir de laquelle on considère le "fond"
export const HYSTERESIS_DEG = 3;   // Marge de tolérance lorsqu'on sort à peine du cône
export const VIS_STICK_MS = 600; // On conserve l'étiquette environ 0,8s après la sortie du cône
export const SMOOTHING_ALPHA_HEADING = .12;  // Lissage de l'azimut (plus stable)
export const SMOOTHING_ALPHA_PITCH = .15;    // Lissage du tangage (plus stable)
export const HEADING_DEADZONE = 2;         // Ignore les changements inférieurs à 1,5°
export const PITCH_DEADZONE = 1.0;           // Ignore les changements inférieurs à 1,0°
export const MIN_DISTANCE = 50;              // Distance minimale en mètres
export const MAX_DISTANCE = 5000;            // Distance maximale en mètres