// Auto-generated map of audio files for features.
// Keys are the exact `nom` values used in the GeoJSON features.
const audioMap: Record<string, any> = {
  "An Daoualhenn": require('./An Daoualhenn.wav'),
  "An Dizoudoù": require('./An Dizoudoù.wav'),
  "An Ivern": require('./An Ivern.wav'),
  "Ar Briellog": require('./Ar Briellog.wav'),
  "Ar Fourn": require('./Ar Fourn.wav'),
  "Ar Garreg Krenn": require('./Ar Garreg Krenn.wav'),
  "Ar Garreg Wenn": require('./Ar Garreg Wenn.wav'),
  "Ar Garreg": require('./Ar Garreg.wav'),
  "Ar Gouelini": require('./Ar Gouelini.wav'),
  "Ar Pil Kreiz": require('./Ar Pil Kreiz.wav'),
  "Ar Pilou Du": require('./Ar Pilou Du.wav'),
  "Ar Pladennoù": require('./Ar Pladennoù.wav'),
  "Ar Raé": require('./Ar Raé.wav'),
  "Ar Roc'h Distag": require("./Ar Roc'h Distag.wav"),
  "Ar Roc'h War Laez ar Guiniveier": require("./Ar Roc'h War Laez ar Guiniveier.wav"),
  "Ar Roc'h War-laez ar Spernennoù": require("./Ar Roc'h War-laez ar Spernennoù.wav"),
  "Ar Spernenn Vihan": require('./Ar Spernenn Vihan.wav'),
  "Ar Spernenn Vraz": require('./Ar Spernenn Vraz.wav'),
  "Ar Vein Dan": require('./Ar Vein Dan.wav'),
  "Beg Pil Yann": require('./Beg Pil Yann.wav'),
  "Belerig Vraz": require('./Belerig Vraz.wav'),
  "Brellum Goz Vihan": require('./Brellum Goz Vihan.wav'),
  "Brellum Goz": require('./Brellum Goz.wav'),
  "Brellum": require('./Brellum.wav'),
  "Brestou": require('./Brestou.wav'),
  "Govelig Vihan": require('./Govelig Vihan.wav'),
  "Govelig Vraz": require('./Govelig Vraz.wav'),
  "Henguer": require('./Henguer.wav'),
  "Ilgouarn": require('./Ilgouarn.wav'),
  "Karreg Mari Go": require('./Karreg Mari Go.wav'),
  "Karreg Sanig Varou": require('./Karreg Sanig Varou.wav'),
  "Karreg Vraz": require('./Karreg Vraz.wav'),
  "Karreg al Lostog": require('./Karreg al Lostog.wav'),
  "Kibell": require('./Kibell.wav'),
  "Kiniveier Vihan": require('./Kiniveier Vihan.wav'),
  "Kiniveier Vraz": require('./Kiniveier Vraz.wav'),
  "Korre Kignet": require('./Korre Kignet.wav'),
  "Koz Stal Goz": require('./Koz Stal Goz.wav'),
  "Koz Stal Nevez": require('./Koz Stal Nevez.wav'),
  "Leguestenn Vihan": require('./Leguestenn Vihan.wav'),
  "Leguestenn Vraz": require('./Leguestenn Vraz.wav'),
  "Lochouarn": require('./Lochouarn.wav'),
  "Mean Feizog": require('./Mean Feizog.wav'),
  "Mean Pig Bihan": require('./Mean Pig Bihan.wav'),
  "Mean Pig Braz": require('./Mean Pig Braz.wav'),
  "Mean Porz Laer": require('./Mean Porz Laer.wav'),
  "Mean Sonn": require('./Mean Sonn.wav'),
  "Mean ar Hrilh": require('./Mean ar Hrilh.wav'),
  "Merouioù": require('./Merouioù.wav'),
  "Ormelog": require('./Ormelog.wav'),
  "Penn Toull al Lien": require('./Penn Toull al Lien.wav'),
  "Penn ar Manac'h": require("./Penn ar Manac'h.wav"),
  "Penn ar Marc'h": require("./Penn ar Marc'h.wav"),
  "Pil An Digo": require('./Pil An Digo.wav'),
  "Pil Ar Jardin": require('./Pil Ar Jardin.wav'),
  "Pil Bihan Henguer": require('./Pil Bihan Henguer.wav'),
  "Pil Mariannig Salou": require('./Pil Mariannig Salou.wav'),
  "Pil Plad": require('./Pil Plad.wav'),
  "Pil Serz": require('./Pil Serz.wav'),
  "Pil Sonn d'an Aod": require("./Pil Sonn d'an Aod.wav"),
  "Pil Sonn da Veaz": require('./Pil Sonn da Veaz.wav'),
  "Pil an Touilhed": require('./Pil an Touilhed.wav'),
  "Pilar Piroun": require('./Pilar Piroun.wav'),
  "Pilar Vartoloded": require('./Pilar Vartoloded.wav'),
  "Piloùar Fank Du": require('./Piloùar Fank Du.wav'),
  "Pont Ulvennoù": require('./Pont Ulvennoù.wav'),
  "Reier Mên Lus": require('./Reier Mên Lus.wav'),
  "Reier Porz Ili": require('./Reier Porz Ili.wav'),
  "Reier an Arhant": require('./Reier an Arhant.wav'),
  "Reier ar Besketerien": require('./Reier ar Besketerien.wav'),
  "Reier ar Har Vihan": require('./Reier ar Har Vihan.wav'),
  "Roc'h Charlez": require("./Roc'h Charlez.wav"),
  "Roc'h Fench Yann Goz": require("./Roc'h Fench Yann Goz.wav"),
  "Roc'h Karre": require("./Roc'h Karre.wav"),
  "Roc'h Kleuz": require("./Roc'h Kleuz.wav"),
  "Roc'h Kola": require("./Roc'h Kola.wav"),
  "Roc'h Pell": require("./Roc'h Pell.wav"),
  "Roc'h an Dour": require("./Roc'h an Dour.wav"),
  "Roc'h ar Roeioù": require("./Roc'h ar Roeioù.wav"),
  "Rochounog Vihan": require('./Rochounog Vihan.wav'),
  "Rochounog Vraz": require('./Rochounog Vraz.wav'),
  "Roh An Tonnou": require('./Roh An Tonnou.wav'),
  "Tonnoù Chep": require('./Tonnoù Chep.wav'),
  "Ulvennou Pell": require('./Ulvennou Pell.wav'),
  "Ulvennoù Kreiz": require('./Ulvennoù Kreiz.wav'),
  "cKoz Stal Goz": require('./cKoz Stal Goz.wav')
};

export default audioMap;
